//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeHouseEntities1 : DbContext
    {
        public CoffeeHouseEntities1()
            : base("name=CoffeeHouseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<SaleProduct> SaleProduct { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Suppilers> Suppilers { get; set; }
        public virtual DbSet<VW_Auth> VW_Auth { get; set; }
        public virtual DbSet<VW_AuthStaff> VW_AuthStaff { get; set; }
        public virtual DbSet<VW_Product> VW_Product { get; set; }
        public virtual DbSet<VW_Staff> VW_Staff { get; set; }
        public virtual DbSet<VW_Supp> VW_Supp { get; set; }
    }
}
